### ISSUE TITLE
Parsing day, month, and year

### ISSUE THREAD

**Issue by MattNguyen** [radar/chronic#2]
We currently have requirements to parse arbitrary date formats. Some of the formats we receive from these systems format dates in the following manner: `17-MAR-16`, where `17` is the day, `MAR` is the month, and `16` is the year.

Is there an easy path to support date formats with years? I noticed `Chronic.Tokenizer.tokenize/2` parses `17-MAR-16` to  `[number: 15, month: 3, number: 16]`, which causes `Chronic.process/2` to not to match. Should `Chronic.Tokenizer.tokenize/2` return `[number: 15, month: 3, year: 16]`, or `Chronic.process/2` to properly match and make assumptions about the year, or both?

Let me know how I can help!

**Comment by radar** [comment]
I think `Chronic.process` should make the assumption that if it's passed something such as `[number: 17, month: 3, number: 16]` that it is in the "day/month/year" format, and so then it should act accordingly. 

This behaviour might even be different if the first number is greater than 31.

**Comment by radar** [comment]
Please submit a patch to attend to that.

**Comment by radar** [comment]
Fixed by #3.
