### ISSUE TITLE
Add support for other date/time parsing libs

### ISSUE THREAD

**Issue by MattNguyen** [radar/chronic#4]
Currently chronic depends on calendar for date/time parsing. However there may be cases where developers are already using Timex or something else for their date/time parsing needs, making the addition of chronic with its dependency on calendar redundant and unnecessary.

My suggestion would be to leverage the adapter pattern and define the behavior for a `parsing_backend` that would handle interactions with the parsing lib. https://github.com/keichan34/exfile does this for file uploads to s3, b2, etc.

What do you think?

**Comment by radar** [comment]
I don't think this is required. To support that kind of thing in this library would only lead to making the code more complex than it needs to be.
