### ISSUE TITLE
Move to Elixir 1.4 built-in calendar support

### ISSUE THREAD

**Issue by venkatd** [radar/chronic#9]
Because Elixir 1.4 has built in calendar types, I think it's worth deprecating the use of `Calendar.NaiveDateTime` and using `NaiveDateTime`. Thoughts?

What's involved to do this? I don't mind submitting a PR.

**Comment by venkatd** [comment]
Realized that the `Calendar` also deprecated these structs so I just had to update those versions. #10

**Comment by radar** [comment]
While I think this would be good to do down the track, this enforces Elixir 1.4. I would like to support anything from Elixir 1.3 and up for now.

Thank you for your time :)

**Comment by cjbottaro** [comment]
Elixir 1.7 is releasing soon, I think it's time to move forward.

You can also make 2.x support Elixir 1.3 and 3.x for Elixir 1.4 and onward.

**Comment by radar** [comment]
@cjbottaro: Sure thing. It looks like #10 has only done half the work so far though. Would you mind taking on the remainder of? That is: moving away from `Calendar.NaiveDateTime` to `NaiveDateTime` instead.

**Comment by radar** [comment]
Thanks @cjbottaro! All the tests are passing here. Everything seems fine. I've now released v3 of Chronic with your changes included.
